### ISSUE TITLE
Feature Request - FastUART 0

### ISSUE THREAD

**Issue by poofik** [jsphuebner/stm32-sine#1]
Currently there is "fastuart" command which sets speed to 921600 baud (1Mbps). Can there be "fastuart 1" and "fastuart 0" to set speed back to 115200 on the fly?

**Comment by jsphuebner** [comment]
Sure, sounds like a plan.
BTW you can fork the repository to your own account, make changes, branch them off and then make a pull request here. https://help.github.com/articles/creating-a-pull-request/

**Comment by jsphuebner** [comment]
I added it to the last commit
