### ISSUE TITLE
Missing updater.py script?

### ISSUE THREAD

**Issue by annerajb** [jsphuebner/stm32-sine#2]
The readme.md makes reference to an updater.py script on the last line is this deprecated or just missing from the repo?

**Comment by jsphuebner** [comment]
Hi, it's part of the boot loader project: https://github.com/jsphuebner/tumanako-inverter-fw-bootloader

**Comment by annerajb** [comment]
Thanks I was able to get it booting after enabling debug symbols on both
and finding that I was hitting a interrupt for not having the encoder plug
in. Uart is devoid of any messages is this normal? Is there a compile flag
to at least print a firmware booted messages right now I only see the magic
bytes sent by the bootloader upon restart as part of the firmware update
protocol

**Comment by jsphuebner** [comment]
Don't really understand...
But no, there are no messages at boot up. Only prints things when requested so.
