### ISSUE TITLE
Square root of sums of squares

### ISSUE THREAD

**Issue by catphish** [jsphuebner/stm32-sine#29]
I previously wrote this code: https://github.com/jsphuebner/stm32-sine/blob/master/src/pwmgeneration-sine.cpp#L188..L196

However it's come to my attention that this is not safe for values of current above about 1000A because of 32 bit integer overflow during multiplication.

I would therefore propose we add a couple of fixed point math functions (one with 3 parameters and one with 2) to help with such calculations:

```
u32fp fp_hypot3 (s32fp a, s32fp b, s32fp c) {
  int n = 0;
  while(a > 16384 || b > 16384 || c > 16384) {
    n++;
    a /= 2;
    b /= 2;
    c /= 2;
  }
  u32fp result = fp_sqrt(FP_MUL(a,a) + FP_MUL(b,b) + FP_MUL(c,c));
  return result << n;
}
```

The idea here is to scale down the values until the calculation is safe. This appears to produce accurate results, but any feedback would be appreciated.

**Comment by jsphuebner** [comment]
Very good.
Just doesn't seem to work for negative numbers, right?

**Comment by catphish** [comment]
You're right, my mistake. Hopefully just be a matter of comparing to -16384 as well as +16384 well on the input. I'll check.

**Comment by catphish** [comment]
I've just submitted a pull request to libopeninv (master), however I'm a little confused as this repo (stm32-sine) repo links to a diverged branch of libopninv. Can this be reconciled somehow so that my proposed new code finds its way into this project?

**Comment by davefiddes** [comment]
stm32-sine uses the "float" branch of libopeninv rather than "master".
