### ISSUE TITLE
Not compile ver5.24 

### ISSUE THREAD

**Issue by sergeynik77** [jsphuebner/stm32-sine#30]
include/vehiclecontrol.h:30:26: error: 'Can' has not been declared
in libopenlib class Can changed to Stm32Can

**Comment by jsphuebner** [comment]
Please pull a fresh clone of the master branch and
`make get-deps`

**Comment by sergeynik77** [comment]
it didn't help
in   \include\vehiclecontrol.h

static void SetCan(Can* val) { can = val; }

in \libopeninv\include\stm32_can.h
c
lass Stm32Can: public CanHardware
{
public:
Stm32Can(uint32_t baseAddr, enum baudrates baudrate, bool remap = false);


modules from
	path = libopencm3
	url = https://github.com/jsphuebner/libopencm3

	path = libopeninv
	url = https://github.com/jsphuebner/libopeninv.git


 make
  CPP     obj/stm32_sine.o

In file included from src/stm32_sine.cpp:44:
include/vehiclecontrol.h:30:26: error: 'Can' has not been declared
   30 |       static void SetCan(Can* val) { can = val; }
      |                          ^~~
include/vehiclecontrol.h:41:14: error: 'Can' does not name a type
   41 |       static Can* can; //!< Member variable "can"
      |              ^~~

**Comment by sergeynik77** [comment]
work with 

https://github.com/jsphuebner/libopeninv/tree/float

**Comment by davefiddes** [comment]
Looks like the submodules are in a confused state. If you follow Johannes instructions it works:

```text
[dave@snowman ~]$ cd /tmp/
[dave@snowman tmp]$ git clone git@github.com:jsphuebner/stm32-sine.git
Cloning into 'stm32-sine'...
remote: Enumerating objects: 1714, done.
remote: Counting objects: 100% (589/589), done.
remote: Compressing objects: 100% (164/164), done.
remote: Total 1714 (delta 481), reused 499 (delta 425), pack-reused 1125
Receiving objects: 100% (1714/1714), 1.46 MiB | 987.00 KiB/s, done.
Resolving deltas: 100% (1209/1209), done.
[dave@snowman tmp]$ cd stm32-sine/
[dave@snowman stm32-sine]$ make get-deps
  GIT SUBMODULE
Submodule 'libopencm3' (https://github.com/jsphuebner/libopencm3) registered for path 'libopencm3'
Submodule 'libopeninv' (https://github.com/jsphuebner/libopeninv.git) registered for path 'libopeninv'
Cloning into '/tmp/stm32-sine/libopencm3'...
Cloning into '/tmp/stm32-sine/libopeninv'...
Submodule path 'libopencm3': checked out '5ba1bb5f8b0287a0ccec9def20f3a6185c3a2a8e'
Submodule path 'libopeninv': checked out '350fc7599dea0db65e5dbf89805250f4fdeee2d0'
  MAKE libopencm3
make[1]: Entering directory '/tmp/stm32-sine/libopencm3'
  GENHDR  stm32/f0
  GENHDR  stm32/f1
  GENHDR  stm32/f2
 ...
  CC      systick.c
  CC      scb.c
  CC      nvic.c
  CC      assert.c
  CC      sync.c
  CC      dwt.c
  AR      libopencm3_pac55xx.a
make[1]: Leaving directory '/tmp/stm32-sine/libopencm3'
[dave@snowman stm32-sine]$ make
  CPP     obj/stm32_sine.o
  CPP     obj/hwinit.o
  CPP     obj/stm32scheduler.o
  CPP     obj/params.o
 ...
  CPP     obj/terminalcommands.o
  CPP     obj/vehiclecontrol.o
  CPP     obj/pwmgeneration-sine.o
  LD      stm32_sine
  OBJCOPY stm32_sine.bin
  OBJCOPY stm32_sine.hex
   text	   data	    bss	    dec	    hex	filename
  46092	   4200	    988	  51280	   c850	stm32_sine
[dave@snowman stm32-sine]$ 
```

**Comment by sergeynik77** [comment]
it doesn't work for me not in windows not in linux

PS C:\avr\openinvertor\inverter> make get-deps
  GIT SUBMODULE
fatal: not a git repository (or any of the parent directories): .git
make: *** [Makefile:146: get-deps] Error 128
PS C:\avr\openinvertor\inverter>

**Comment by sergeynik77** [comment]
thank you so works
PS C:\tmp> git clone https://github.com/jsphuebner/stm32-sine.git
Cloning into 'stm32-sine'...
remote: Enumerating objects: 1714, done.
remote: Counting objects: 100% (589/589), done.
remote: Compressing objects: 100% (163/163), done.
remote: Total 1714 (delta 480), reused 500 (delta 426), pack-reused 1125
Receiving objects: 100% (1714/1714), 1.46 MiB | 2.05 MiB/s, done.
Resolving deltas: 100% (1208/1208), done.
PS C:\tmp> cd stm32-sine/
PS C:\tmp\stm32-sine> make get-deps
  GIT SUBMODULE
Submodule 'libopencm3' (https://github.com/jsphuebner/libopencm3) registered for path 'libopencm3'
Submodule 'libopeninv' (https://github.com/jsphuebner/libopeninv.git) registered for path 'libopeninv'
Cloning into 'C:/tmp/stm32-sine/libopencm3'...
Cloning into 'C:/tmp/stm32-sine/libopeninv'...
Submodule path 'libopencm3': checked out '5ba1bb5f8b0287a0ccec9def20f3a6185c3a2a8e'
Submodule path 'libopeninv': checked out '350fc7599dea0db65e5dbf89805250f4fdeee2d0'
  MAKE libopencm3
make[1]: Entering directory 'C:/tmp/stm32-sine/libopencm3'
  GENHDR  stm32/f0
  GENHDR  stm32/f1

**Comment by sergeynik77** [comment]
i will work on a little change firmware to 29bit canid, to run a lowcost dashboard.
https://aliexpress.com/item/1005004869698739.html


CAN 250k 29bit

config
0x18290bf 8 d0 d1 d2 d3 d4 d5 d6 d7    
d0:d1 whell size mm
d2 impulse per rotate
d3 d4 == 55 aa clear millage 
d6 0x80 -miles 0x00 km

work mode

0x10261051 8 d0 d1 d2 d3 d4 d5 d6 d7    bms
d4 SOC %

0x10261022 8 d0 d1 d2 d3 d4 d5 d6 d7    motor

d0 1 motor 2 motor 4 throttle 8 ecu 10 brake
d1 2 brake 8 herznaet 10 R, 20 1g, 40 P, 60 2g, A0 3g, E0 4g
d3:d2 speed
d5:d4 bat voltage*0.1 (00ff=25.5v)

0x1026105a 8    dashboard transmit

**Comment by sergeynik77** [comment]
thank you all

	if(id==0x321){id=0x10261051;ext=1;}
	if(id==0x322){id=0x10261022;ext=1;}
![photo_2023-02-12_17-31-00](https://user-images.githubusercontent.com/88606103/218317179-dfa84d8a-48d0-4c1e-8d78-67747583e415.jpg)
![photo_2023-02-12_17-31-26](https://user-images.githubusercontent.com/88606103/218317182-719eb5a3-2936-44fb-b890-51fe332b7a2f.jpg)

**Comment by sergeynik77** [comment]
![photo_2023-02-12_17-33-05](https://user-images.githubusercontent.com/88606103/218317246-c364a063-ef56-48d1-9cd0-858542571f9b.jpg)

**Comment by jsphuebner** [comment]
Cool :)
