### ISSUE TITLE
Heatsink and Motor temperatures are unfiltered

### ISSUE THREAD

**Issue by davefiddes** [jsphuebner/stm32-sine#31]
Found by code inspection. In `void VehicleControl::CalcAndOutputTemp()` the heatsink (tmphs) and motor (tmpm) are carefully filtered with IIRFILTERF(). The filtered values are never used. The unfiltered values are assigned to `Param::tmphs` and `Param::tmpm` at the end of the function. This doesn't seem intentional or desirable.

**Comment by jsphuebner** [comment]
Oh wow, this bug must be a decade old! And I always wondered why the values were unsmooth despite all the filtering. So will lower the filter constants quite a bit...
