### ISSUE TITLE
Feature Request: Implement regen throttle curve without dead zone

### ISSUE THREAD

**Issue by catphish** [jsphuebner/stm32-sine#38]
At the moment, the openinverter throttle curve includes a fixed percentage of travel dedicated to regen, and a fixed percentage dedicated to acceleration. Many users do not like the dead zone that this creates.

There have been a couple of discussions and proposed solutions to this problem:
https://openinverter.org/forum/viewtopic.php?p=62626
https://openinverter.org/forum/viewtopic.php?p=42509

The purpose of this issue it to track possible solutions to eliminate the dead zone. I believe any solution will be a form of two dimensional throttle map that takes both the pot input and the motor speed, and outputs a torque request accordingly.

**Comment by amattila** [comment]
I post the same here, as what I posted on forums to get conversation going on here too:

> I made some changes to my regen code, to CalcThrottle() -function. I realized that the first one (code that I posted) had a problem. It was when you don't go over that regentravel area. (eg set to 30%), you don't get any regen when lifting the pedal (until off throttle). And doing 30% of throttle can get you to some speeds already. I started wondering how BMW does this, and noticed that they have different curve for accelerator for the first maybe 20-30%, car moves but it only stars to pick up more power after the regentravel area. So I made similar changes. Here's how it works with regentravel set to 30%.
> 
> Going from 0% pedal to 100% pedal, first 30% you only accelerate 0-10% of the throttle. This makes parking lot manoeuvres easy and helps you initially get over the 30% regentravel "area" - so it's easier to control speed after that. So, after getting over that regentravel (30% of travel) you are at 10% of throttle, so the rest from 30% to 100% is 10%-100% throttle.
> 
> It keeps track of pedal position history, and once you start lifting off the pedal, the curve changes just a bit. Now it's 0-30% for regen and 30-100% for acceleration. So this is the same as current implementation in Johannes's firmware. And it's like this until you do complete stop.
> 
> There is no speed related regen factored in. I don't think it's needed. And of course regenramp and regenrampstr and all parameters works like they have used to.

Btw. Would be great to have multiple implementations for throttle calculation / regen, so that you could just select it from Web Interface.
