### ISSUE TITLE
Reversed field direction in SINE variant

### ISSUE THREAD

**Issue by jsphuebner** [jsphuebner/stm32-sine#40]
Sine firmware seems to generate a stator field rotating anti-clockwise when forward is selected and clockwise otherwise.
It has been discovered by catphish but I can't find the forum post. 

**Please help searching**

As a consequence people using the LDU need to swap the A & B encoder wires and select reverse direction when wanting to go forward. Same goes for the SDU but there the swap is already incorporated into the hardware.
Also the newly introduced "rotordir" spot value indicates this phase swap: https://openinverter.org/forum/viewtopic.php?p=62563#p62563

When fixing this we need to keep backward compatibility in mind. People who use an A/B swapped LDU or SDU shouldn't need to touch their wiring.

Perhaps it's as simple as introducing "pinswap" in sine firmware as well, allowing to swap PWM channels 1 and 2. Encoder channels can't be swapped in software.

**Comment by Mitchy6** [comment]
Is this something relating to the issue?
[url]https://openinverter.org/forum/viewtopic.php?p=52723#p52723[/url]

May also be related to the Current CT Swap?
[url]https://openinverter.org/forum/viewtopic.php?p=50975#p50975[/url]

**Comment by jsphuebner** [comment]
Yes that's the post I was looking for, thanks.

Swapped current sensors are not relevant in sine firmware

**Comment by jsphuebner** [comment]
Added pinswap to sine firmware 730dfa3
