### ISSUE TITLE
Sine_5.35R Not saving CAN MAP of POT2

### ISSUE THREAD

**Issue by JJ0z** [jsphuebner/stm32-sine#45]
Currently running version 5.35R-Sine. When mapping POT2 to CAN messages, the software states that its save. When power cycling the board( turning on/off) the CAN map is no longer there. When reverting to version 5.27R-Sine, the POT2 CAN map is shown correctly. When reverting back to version 5.35R-Sine, the CAN MAP disappears. 

Any idea why?

**Comment by jsphuebner** [comment]
This is intended for safety reasons: https://github.com/jsphuebner/stm32-sine/tree/v5.32.R

**Comment by jsphuebner** [comment]
Also read here: https://openinverter.org/wiki/CAN_communication
